#!/bin/sh

if [ -d /usr/lib/ccache ]; then
    export PATH="/usr/lib/ccache:$PATH"
fi
export HOME="$(mktemp -d)"
mkdir "$HOME/runtime"
export XDG_RUNTIME_DIR="$HOME/runtime"
debian/rules clean 2>&1
dpkg-source --before-build .
debian/rules build 2>&1
xvfb-run -a --server-args="-screen 0 1024x768x24+32" \
    dbus-launch --exit-with-session debian/tests/testsuite.xsession
ret=$?
rm -rf debian/tests.home
exit $ret
